import Form from "./Form";

export const metadata = {
	title: "Contact | Innovation 3.0",
	description: "Generated by create next app",
};

const page = () => {
	return (
		<div className="contactpage">
			<div className="container">
				<h2>Contact us</h2>
				<Form />
			</div>
		</div>
	);
};

export default page;
