import { Montserrat } from "next/font/google";
import "../styles/styles.css";
import Header from "@/components/Header";

const montserrat = Montserrat({
	subsets: ["latin"],
	weight: ["400", "700", "800"],
});

export const metadata = {
	title: "Innovation 3.0",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={montserrat.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
