export const metadata = {
	title: "404 | Innovation 3.0",
	description: "Generated by create next app",
};

const notFound = () => {
	return (
		<div className="notfoundpage">
			<h1>404</h1>
			<p> Page not find</p>
		</div>
	);
};

export default notFound;
