import Form from "./Form";

export const metadata = {
	title: "Register | Innovation 3.0",
	description: "Generated by create next app",
};

const page = () => {
	return (
		<div className="pre-registerpage">
			<div className="container">
				<h2>Dare | Dream | Innovate</h2>
				<Form />
			</div>
		</div>
	);
};

export default page;
