export const metadata = {
	title: "Cornerstone foundations",
	description: "Generated by create next app",
};

const page = () => {
	return (
		<div className="cornerstone-foundation">
			<h2>CORNERSTONE FOUNDATION</h2>
			<h4>COMING SOON...</h4>
		</div>
	);
};

export default page;
